server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rockycres/spring-config-repo-microsvc-suite
          search-paths:
            - 'service-config/*service'
          username: xx@gmail.com
          password: xxx
          skipSslValidation: true
          default-label: master



eureka:
  instance:
    prefer-ip-address: true
